### Q1 Dataset Exploration

Perform the following exploratory steps:
- Display the first 10 rows
- Display the dataset structure using `info()`
- Find the number of rows and columns
- Identify the data types of each column

In [6]:
print('First 10 rows of the dataset:')
display(df.head(10))

print('\nDataset structure and data types:')
df.info()

print(f'\nNumber of rows: {df.shape[0]}')
print(f'Number of columns: {df.shape[1]}')

print('\nData types of each column:')
print(df.dtypes)

First 10 rows of the dataset:

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
0,1001,2024-10-01,Priya,Hyderabad,East,Mouse,Accessories,1735,7,0.00,307.52
1,1002,2024-05-03,Sneha,Kolkata,East,Monitor,Electronics,807,2,0.15,49.89
2,1003,2024-01-26,Anita,Mumbai,West,Phone,Electronics,2328,1,0.20,66.47
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
5,1006,2024-07-04,Pooja,Bangalore,West,Printer,Office,3073,8,0.20,191.58
6,1007,2024-06-24,Dev,Chennai,East,Monitor,Electronics,1170,5,0.20,22.83
7,1008,2024-03-18,Kavya,Kolkata,East,Phone,Electronics,4693,7,0.05,918.49
8,1009,2024-10-31,Kavya,Ahmedabad,East,Phone,Electronics,5071,6,0.10,707.55
9,1010,2024-12-25,Pooja,Ahmedabad,North,Phone,Electronics,2711,8,0.00,477.32

Dataset structure and data types:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    230 non-null    int64
 1   Order_Date  230 non-null    object
 2   Customer    230 non-null    object
 3   City        230 non-null    object
 4   Region      230 non-null    object
 5   Product     230 non-null    object
 6   Category    230 non-null    object
 7   Sales       230 non-null    int64
 8   Quantity    230 non-null    int64
 9   Discount    230 non-null    float64
 10  Profit      230 non-null    float64
dtypes: float64(2), int64(3), object(6)
memory usage: 19.9+ KB

Number of rows: 230
Number of columns: 11

Data types of each column:
Order_ID        int64
Order_Date     object
Customer       object
City           object
Region         object
Product        object
Category       object
Sales           int64
Quantity        int64
Discount      float64
Profit        float64
dtype: object

### Q2 Sales Filtering Analysis

Filter the dataset to display:

*   Orders where Sales > 3500
*   Orders where Region = "East" and Sales > 2500

Explain what insights you observe.

In [7]:
# Orders where Sales > 3500
sales_gt_3500 = df[df['Sales'] > 3500]
print('Orders where Sales > 3500:')
display(sales_gt_3500)

Orders where Sales > 3500:

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
7,1008,2024-03-18,Kavya,Kolkata,East,Phone,Electronics,4693,7,0.05,918.49
8,1009,2024-10-31,Kavya,Ahmedabad,East,Phone,Electronics,5071,6,0.10,707.55
10,1011,2024-06-30,Neha,Delhi,South,Printer,Office,5977,6,0.00,1578.32
...,...,...,...,...,...,...,...,...,...,...,...
219,1220,2024-03-22,Meera,Bangalore,West,Phone,Electronics,5986,7,0.05,986.70
222,1223,2024-03-04,Meera,Ahmedabad,South,Phone,Electronics,4356,6,0.10,416.87
223,1224,2024-01-07,Dev,Bangalore,East,Tablet,Electronics,4115,4,0.05,870.03
225,1226,2024-06-14,Anita,Ahmedabad,East,Laptop,Electronics,5647,2,0.15,662.00
229,1230,2024-04-13,Meera,Kolkata,North,Monitor,Electronics,5087,8,0.10,416.72

In [8]:
# Orders where Region = 'East' and Sales > 2500
east_region_sales_gt_2500 = df[(df['Region'] == 'East') & (df['Sales'] > 2500)]
print('\nOrders where Region = "East" and Sales > 2500:')
display(east_region_sales_gt_2500)

Orders where Region = "East" and Sales > 2500:

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
7,1008,2024-03-18,Kavya,Kolkata,East,Phone,Electronics,4693,7,0.05,918.49
8,1009,2024-10-31,Kavya,Ahmedabad,East,Phone,Electronics,5071,6,0.10,707.55
13,1014,2024-03-18,Anita,Bangalore,East,Mouse,Accessories,3616,4,0.05,463.93
21,1022,2024-01-14,Nitin,Chennai,East,Monitor,Electronics,4827,6,0.05,912.34
27,1028,2024-07-21,Dev,Kolkata,East,Tablet,Electronics,4054,6,0.00,1013.83
33,1034,2024-12-15,Nitin,Ahmedabad,East,Tablet,Electronics,4378,2,0.20,-104.30
34,1035,2024-02-20,Nitin,Ahmedabad,East,Laptop,Electronics,2535,4,0.10,188.15
41,1042,2024-07-15,Rohan,Chennai,East,Laptop,Electronics,3268,8,0.15,295.15
43,1044,2024-09-20,Kavya,Hyderabad,East,Printer,Office,2618,7,0.05,454.64
52,1053,2024-05-24,Anita,Chennai,East,Phone,Electronics,5949,7,0.20,220.44
55,1056,2024-01-03,Sneha,Chennai,East,Headphones,Accessories,2784,4,0.05,474.60
58,1059,2024-12-30,Anita,Delhi,East,Tablet,Electronics,4790,1,0.20,238.53
60,1061,2024-02-05,Nitin,Delhi,East,Monitor,Electronics,4508,5,0.00,972.35
70,1071,2024-05-28,Vikas,Hyderabad,East,Mouse,Accessories,3762,2,0.05,719.68
71,1072,2024-05-20,Rahul,Chennai,East,Printer,Office,3696,2,0.10,600.75
73,1074,2024-10-10,Sara,Bangalore,East,Mouse,Accessories,4004,1,0.15,445.81
74,1075,2024-11-25,Pooja,Ahmedabad,East,Laptop,Electronics,3865,8,0.20,174.96
76,1077,2024-03-02,Neha,Pune,East,Monitor,Electronics,2964,8,0.20,109.33
81,1082,2024-08-16,Isha,Chennai,East,Phone,Electronics,2720,4,0.15,163.13
87,1088,2024-07-29,Pooja,Mumbai,East,Headphones,Accessories,4811,4,0.20,-25.47
92,1093,2024-01-13,Karan,Kolkata,East,Laptop,Electronics,5372,3,0.15,136.64
96,1097,2024-06-07,Isha,Delhi,East,Phone,Electronics,5096,4,0.15,283.66
98,1099,2024-07-26,Rahul,Kolkata,East,Laptop,Electronics,5674,7,0.05,1141.51
108,1109,2024-10-23,Raj,Hyderabad,East,Tablet,Electronics,2509,4,0.05,371.67
109,1110,2024-11-28,Priya,Ahmedabad,East,Printer,Office,2561,4,0.20,57.96
112,1113,2024-11-01,Meera,Bangalore,East,Tablet,Electronics,4179,5,0.00,754.64
113,1114,2024-05-10,Rahul,Bangalore,East,Mouse,Accessories,3285,3,0.00,625.46
116,1117,2024-12-07,Pooja,Kolkata,East,Tablet,Electronics,3758,5,0.15,446.54
128,1129,2024-06-09,Nitin,Delhi,East,Laptop,Electronics,5713,3,0.00,1498.02
139,1140,2024-05-04,Karan,Ahmedabad,East,Monitor,Electronics,3500,8,0.05,467.16
141,1142,2024-01-01,Rahul,Mumbai,East,Headphones,Accessories,5430,8,0.05,741.25
146,1147,2024-05-31,Raj,Delhi,East,Keyboard,Accessories,5709,7,0.20,383.58
152,1153,2024-02-27,Rahul,Mumbai,East,Phone,Electronics,3644,2,0.05,512.25
156,1157,2024-05-27,Neha,Kolkata,East,Laptop,Electronics,4906,4,0.00,1115.89
171,1172,2024-09-22,Neha,Hyderabad,East,Headphones,Accessories,4228,1,0.20,236.15
179,1180,2024-12-13,Neha,Ahmedabad,East,Monitor,Electronics,2690,7,0.10,452.70
182,1183,2024-12-01,Pooja,Chennai,East,Laptop,Electronics,5884,1,0.05,1266.10
185,1186,2024-03-12,Kavya,Ahmedabad,East,Phone,Electronics,5047,2,0.10,564.78
187,1188,2024-07-10,Isha,Kolkata,East,Mouse,Accessories,4333,8,0.10,667.53
193,1194,2024-07-23,Pooja,Delhi,East,Laptop,Electronics,3767,7,0.20,103.23
197,1198,2024-10-16,Rahul,Ahmedabad,East,Tablet,Electronics,3955,1,0.10,284.92
202,1203,2024-05-10,Rahul,Mumbai,East,Phone,Electronics,2901,8,0.15,252.25
207,1208,2024-04-29,Dev,Chennai,East,Monitor,Electronics,3585,7,0.15,287.44
216,1217,2024-08-16,Karan,Chennai,East,Monitor,Electronics,2643,5,0.15,78.53
223,1224,2024-01-07,Dev,Bangalore,East,Tablet,Electronics,4115,4,0.05,870.03
225,1226,2024-06-14,Anita,Ahmedabad,East,Laptop,Electronics,5647,2,0.15,662.00
228,1229,2024-09-04,Priya,Pune,East,Tablet,Electronics,2635,8,0.00,531.76

#### Q3 Customer Purchase Analysis Identify the top 5 customers based on total sales. Hint: Use GroupBy with aggregation

In [10]:

top_customers = df.groupby('Customer')['Sales'].sum().reset_index()


top_5_customers = top_customers.sort_values(by='Sales', ascending=False).head(5)

print('Top 5 Customers based on Total Sales:')
display(top_5_customers)

Top 5 Customers based on Total Sales:

   Customer  Sales
9     Nitin  59820
13      Raj  58416
12    Rahul  52291
3       Dev  48500
4      Isha  46818

### Q4 Regional Sales Performance

Calculate the total sales generated by each region.

Then identify:

Which region generated the highest revenue?

In [11]:
# Calculate total sales by region
regional_sales = df.groupby('Region')['Sales'].sum().reset_index()

print('Total Sales by Region:')
display(regional_sales)

# Identify the region with the highest revenue
highest_revenue_region = regional_sales.loc[regional_sales['Sales'].idxmax()]

print(f'\nThe region with the highest revenue is {highest_revenue_region['Region']} with total sales of {highest_revenue_region['Sales']}.')

Total Sales by Region:

  Region   Sales
0   East  232675
1  North  158210
2  South  183108
3   West  170227

The region with the highest revenue is East with total sales of 232675.

### Q5 Product Performance Analysis

Calculate the total quantity sold for each product.

Which product appears to be the most popular?

In [12]:
# Calculate total quantity sold by product
product_quantities = df.groupby('Product')['Quantity'].sum().reset_index()

print('Total Quantity Sold by Product:')
display(product_quantities)

# Identify the most popular product (highest quantity sold)
most_popular_product = product_quantities.loc[product_quantities['Quantity'].idxmax()]

print(f'\nThe most popular product is {most_popular_product['Product']} with a total of {most_popular_product['Quantity']} units sold.')

Total Quantity Sold by Product:

      Product  Quantity
0  Headphones       115
1    Keyboard       110
2      Laptop       140
3     Monitor       156
4       Mouse       122
5       Phone       151
6     Printer       108
7      Tablet       150

The most popular product is Monitor with a total of 156 units sold.

### Q6 Multi-Level Grouping

Group the dataset by: Region and Category
Calculate the total sales for each combination.

What insights can you derive from this analysis?

In [13]:
# Group by 'Region' and 'Category' and calculate total sales
regional_category_sales = df.groupby(['Region', 'Category'])['Sales'].sum().reset_index()

print('Total Sales by Region and Category:')
display(regional_category_sales)

Total Sales by Region and Category:

   Region     Category   Sales
0    East  Accessories   57646
1    East  Electronics  160907
2    East       Office   14122
3   North  Accessories   62052
4   North  Electronics   70023
5   North       Office   26135
6   South  Accessories   80914
7   South  Electronics   86690
8   South       Office   15504
9    West  Accessories   64811
10   West  Electronics   84128
11   West       Office   21288

In [ ]:
# Q7 Create the pivot table
pivot_table_sales = df.pivot_table(index='Region', columns='Product', values='Sales', aggfunc='sum')

print('Pivot Table (Region vs. Product Sales):')
display(pivot_table_sales)

if 'Laptop' in pivot_table_sales.columns:
    region_most_laptops = pivot_table_sales['Laptop'].idxmax()
    max_laptop_sales = pivot_table_sales['Laptop'].max()
    print(f'\nThe region that sells the most Laptops is {region_most_laptops} with total sales of {max_laptop_sales}.')
else:
    print('\nLaptop product not found in the dataset.')

### Q8 Profitability Analysis

Calculate the average profit for each product category.

Which category is most profitable?

In [14]:
# Calculate average profit for each product category
category_profit = df.groupby('Category')['Profit'].mean().reset_index()

print('Average Profit by Category:')
display(category_profit)


most_profitable_category = category_profit.loc[category_profit['Profit'].idxmax()]

print(f'\nThe most profitable category is {most_profitable_category['Category']} with an average profit of {most_profitable_category['Profit']:.2f}.')

Average Profit by Category:

      Category      Profit
0  Accessories  410.603086
1  Electronics  396.462114
2       Office  471.938462

The most profitable category is Office with an average profit of 471.94.

### Q9 Discount Impact Study

Analyze the relationship between discount and profit.

Tasks:

*   Calculate the average profit for each discount level
*   Identify whether higher discounts lead to lower profit

In [15]:
# Calculate the average profit for each discount level
discount_profit = df.groupby('Discount')['Profit'].mean().reset_index()

print('Average Profit by Discount Level:')
display(discount_profit)


sorted_discount_profit = discount_profit.sort_values(by='Discount', ascending=True)

print('\nRelationship between Discount and Profit:')
print(sorted_discount_profit.to_string(index=False))


profits = sorted_discount_profit['Profit'].tolist()
discounts = sorted_discount_profit['Discount'].tolist()

if len(profits) > 1:
    # Simple check: if profit generally decreases as discount increases
    # This is a basic heuristic, more robust statistical tests could be used for a definitive answer
    is_decreasing = all(profits[i] >= profits[i+1] for i in range(len(profits) - 1) if discounts[i] < discounts[i+1])

    if is_decreasing:
        print('\nObservation: Higher discounts appear to generally lead to lower average profit.')
    else:
        print('\nObservation: The relationship between discount and average profit is not consistently inverse (i.e., higher discounts do not always lead to lower average profit).')

Average Profit by Discount Level:

   Discount      Profit
0      0.00  751.210588
1      0.05  531.368039
2      0.10  346.460513
3      0.15  237.191400
4      0.20   90.026923

Relationship between Discount and Profit:
 Discount     Profit
     0.00 751.210588
     0.05 531.368039
     0.10 346.460513
     0.15 237.191400
     0.20  90.026923

Observation: Higher discounts appear to generally lead to lower average profit.

### Q10 End-to-End Data Wrangling Task

Perform the following workflow:

*   Filter the dataset where Sales > 3000
*   Group data by Region and Product
*   Calculate total sales
*   Reshape the result into a pivot table

Explain the business insights obtained from this analysis.

In [16]:
# 1. Filter the dataset where Sales > 3000
filtered_sales_df = df[df['Sales'] > 3000]
print('Filtered DataFrame (Sales > 3000):')
display(filtered_sales_df.head())

# 2. Group data by Region and Product and calculate total sales
regional_product_sales = filtered_sales_df.groupby(['Region', 'Product'])['Sales'].sum().reset_index()
print('\nTotal Sales by Region and Product (Sales > 3000):')
display(regional_product_sales)

# 3. Reshape the result into a pivot table
pivot_table_high_sales = regional_product_sales.pivot_table(index='Region', columns='Product', values='Sales', aggfunc='sum')
print('\nPivot Table of High Sales by Region and Product:')
display(pivot_table_high_sales)

Filtered DataFrame (Sales > 3000):

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
5,1006,2024-07-04,Pooja,Bangalore,West,Printer,Office,3073,8,0.20,191.58
7,1008,2024-03-18,Kavya,Kolkata,East,Phone,Electronics,4693,7,0.05,918.49
8,1009,2024-10-31,Kavya,Ahmedabad,East,Phone,Electronics,5071,6,0.10,707.55

Total Sales by Region and Product (Sales > 3000):

   Region     Product  Sales
0    East  Headphones  14469
1    East    Keyboard   9642
2    East      Laptop  44096
3    East     Monitor  16420
4    East       Mouse  19000
5    East       Phone  29500
6    East     Printer   3696
7    East      Tablet  29229
8   North  Headphones   5326
9   North    Keyboard  15653
10  North      Laptop   4540
11  North     Monitor   5087
12  North       Mouse  22209
13  North       Phone  24670
14  North     Printer  17185
15  North      Tablet   3392
16  South  Headphones  10026
17  South    Keyboard  19249
18  South      Laptop  17950
19  South     Monitor  14921
20  South       Mouse  26928
21  South       Phone  18218
22  South     Printer  14143
23  South      Tablet  19613
24   West  Headphones  13898
25   West    Keyboard  33380
26   West      Laptop   5922
27   West     Monitor  14354
28   West       Mouse   3511
29   West       Phone  15653
30   West     Printer  12648
31   West      Tablet  17185

Pivot Table of High Sales by Region and Product:

Product  Headphones  Keyboard  Laptop  Monitor  Mouse  Phone  Printer  Tablet
Region
East          14469      9642   44096    16420  19000  29500     3696   29229
North          5326     15653    4540     5087  22209  24670    17185    3392
South         10026     19249   17950    14921  26928  18218    14143   19613
West          13898     33380    5922    14354   3511  15653    12648   17185